name: Build Server

on:
  pull_request: {}
  push:
    paths:
      - 'Dockerfile'
      - './api/MyApp.sln'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: setup .net core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100

      - name: build
        run: dotnet build
        working-directory: ./api

      - name: test
        run: |
          dotnet test
          if [ $? -eq 0 ]; then
            echo TESTS PASSED
          else
            echo TESTS FAILED
            exit 1
          fi
        working-directory: ./api/MyApp.Tests
