name: Build Server

on:
  pull_request: {}
  push:
    paths:
      - 'Dockerfile'
      - './api/MyApp.sln'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: true
    - run: dotnet build ./api
    - run: dotnet test ./api/MyApp.Tests